name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    deploy:
      
        name: Deploy
        runs-on: ubuntu-latest
        env:
          GCP_APP_NAME: "cloud-run-actions-example"
          # IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_APP_NAME }}
                    
        steps:

        - name: Set env variables
          run: echo  "IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_APP_NAME }}" >> $GITHUB_ENV

        
        - name: Login
          # uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
            service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_PRIVATE_KEY }}
            
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . --tag $IMAGE_NAME 

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "go test -v" 

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated


